// session.js
let PH={word:'despondent',pos:'adjective',def:'in low spirits from loss of hope or courage.'};
let ss='idle',rec=null,syn=window.speechSynthesis,wt=false,ttsAudio=null;
function iSess(){ss='idle';document.getElementById('wd').classList.remove('vis');document.getElementById('sbot').classList.remove('cmp');document.getElementById('ach').classList.remove('pop');document.getElementById('vsent').textContent='';document.getElementById('rdot').classList.remove('on');if(ttsAudio){try{ttsAudio.pause();}catch(e){}ttsAudio=null;}setS('listening...');stopT();setL(false);listen();}
function setS(t){document.getElementById('sstat').textContent=t;}
function setL(on){document.getElementById('slogo').classList.toggle('pls',on);}
function startT(){document.getElementById('vbs').classList.add('talk');wt=true;setL(false);}
function stopT(){document.getElementById('vbs').classList.remove('talk');wt=false;}
function updateWordCard(){const w=document.querySelector('.vword'),p=document.querySelector('.vpos'),d=document.querySelector('.vdef');if(w)w.textContent=PH.word;if(p)p.textContent=PH.pos||'word';if(d)d.textContent=PH.def;}
function extractDefineWord(t){const clean=t.toLowerCase().replace(/[^a-z\s'-]/g,' ').replace(/\s+/g,' ').trim();let m=clean.match(/\bdefine\s+([a-z'-]+)/);if(m&&m[1])return m[1];m=clean.match(/\bwhat does\s+([a-z'-]+)\s+mean\b/);if(m&&m[1])return m[1];m=clean.match(/\bmeaning of\s+([a-z'-]+)/);if(m&&m[1])return m[1];return '';}
function articleFor(word){return /^[aeiou]/i.test(word)?'an':'a';}
async function getDefinition(word){try{const r=await fetch(`/api/define?word=${encodeURIComponent(word)}`);if(!r.ok)throw new Error('lookup failed');return await r.json();}catch(e){return {found:false,word};}}
function fallbackSpeak(txt,cb){syn.cancel();const u=new SpeechSynthesisUtterance(txt);u.rate=.95;u.pitch=1.05;u.onend=()=>{stopT();if(cb)cb();};syn.speak(u);}
async function wSay(txt,cb){startT();setS('wordy speaking...');try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:txt})});if(!r.ok)throw new Error('tts failed');const b=await r.blob();if(!b.size)throw new Error('empty audio');if(ttsAudio){try{ttsAudio.pause();}catch(e){}}const url=URL.createObjectURL(b);ttsAudio=new Audio(url);ttsAudio.onended=()=>{URL.revokeObjectURL(url);ttsAudio=null;stopT();if(cb)cb();};ttsAudio.onerror=()=>{URL.revokeObjectURL(url);ttsAudio=null;fallbackSpeak(txt,cb);};await ttsAudio.play();}catch(e){fallbackSpeak(txt,cb);}}
async function handleDefine(t){const word=extractDefineWord(t);if(!word){wSay('Tell me a word to define, like define luminous.',()=>{ss='awaiting_define';setL(true);setS('listening...');});return;}ss='defining';setS('looking up definition...');const lookup=await getDefinition(word);if(!lookup.found){const msg=lookup.error==='not_configured'?'Dictionary service is not configured yet.':'I could not find that word right now.';wSay(`${msg} Try another word.`,()=>{ss='awaiting_define';setL(true);setS('listening...');});return;}PH={word:lookup.word||word,pos:lookup.partOfSpeech||'word',def:(lookup.definition||'').replace(/\.$/,'')+'.'};updateWordCard();document.getElementById('wd').classList.add('vis');document.getElementById('sbot').classList.add('cmp');wSay(`${PH.word} is ${articleFor(PH.pos)} ${PH.pos}, meaning ${PH.def} Would you like to record a sentence?`,()=>{ss='awaiting_yes_no';setL(true);setS('say yes or no...');});}
function listen(){if(!('webkitSpeechRecognition' in window)&&!('SpeechRecognition' in window)){setS('voice not supported');return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;rec=new SR();rec.continuous=true;rec.interimResults=true;rec.lang='en-US';rec.onstart=()=>{setL(true);setS('listening...');};rec.onresult=(e)=>{if(wt)return;let fi='',it='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)fi+=e.results[i][0].transcript.toLowerCase().trim();else it+=e.results[i][0].transcript.toLowerCase().trim();}hH((fi||it).trim(),!!fi);};rec.onerror=(e)=>{if(e.error!=='no-speech')setS('mic error');};rec.onend=()=>{if(ss!=='done'){try{rec.start();}catch(e){}}};try{rec.start();}catch(e){}}
function hH(t,f){if(!t)return;if(ss==='idle'){if(t.includes('hey wordy')){ss='activated';setL(false);wSay('m-hmm',()=>{ss='awaiting_define';setL(true);setS('listening...');});}return;}if(ss==='awaiting_define'){if((t.includes('define')||t.includes('what does')||t.includes('mean'))&&f){handleDefine(t);}return;}if(ss==='awaiting_yes_no'){if(f){if(t.includes('yes')){ss='rec_sent';setS('recording...');document.getElementById('rdot').classList.add('on');document.getElementById('vsent').textContent='';}else if(t.includes('no')){ss='fin';document.getElementById('rdot').classList.remove('on');wSay(`Okay, gotcha. I will only add ${PH.word} and its definition to your library.`,()=>{document.getElementById('ach').classList.add('pop');setTimeout(()=>{ss='done';setTimeout(iSess,2500);},1000);});}}return;}if(ss==='rec_sent'){document.getElementById('vsent').textContent='\u201c'+t+'\u201d';if(f&&t.length>10){ss='fin';document.getElementById('rdot').classList.remove('on');wSay(`Got it! ${PH.word} is on your list.`,()=>{document.getElementById('ach').classList.add('pop');setTimeout(()=>{ss='done';setTimeout(iSess,2500);},1000);});}}}