// session.js
const PH={word:'despondent',pos:'adjective',def:'in low spirits from loss of hope or courage.'};
let ss='idle',rec=null,syn=window.speechSynthesis,wt=false;
function iSess(){ss='idle';document.getElementById('wd').classList.remove('vis');document.getElementById('sbot').classList.remove('cmp');document.getElementById('ach').classList.remove('pop');document.getElementById('vsent').textContent='';document.getElementById('rdot').classList.remove('on');setS('listening...');stopT();setL(false);listen();}
function setS(t){document.getElementById('sstat').textContent=t;}
function setL(on){document.getElementById('slogo').classList.toggle('pls',on);}
function startT(){document.getElementById('vbs').classList.add('talk');wt=true;setL(false);}
function stopT(){document.getElementById('vbs').classList.remove('talk');wt=false;}
function wSay(txt,cb){syn.cancel();startT();setS('wordy speaking...');const u=new SpeechSynthesisUtterance(txt);u.rate=.95;u.pitch=1.05;u.onend=()=>{stopT();if(cb)cb();};syn.speak(u);}
function listen(){if(!('webkitSpeechRecognition' in window)&&!('SpeechRecognition' in window)){setS('voice not supported');return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;rec=new SR();rec.continuous=true;rec.interimResults=true;rec.lang='en-US';rec.onstart=()=>{setL(true);setS('listening...');};rec.onresult=(e)=>{if(wt)return;let fi='',it='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)fi+=e.results[i][0].transcript.toLowerCase().trim();else it+=e.results[i][0].transcript.toLowerCase().trim();}hH((fi||it).trim(),!!fi);};rec.onerror=(e)=>{if(e.error!=='no-speech')setS('mic error');};rec.onend=()=>{if(ss!=='done'){try{rec.start();}catch(e){}}};try{rec.start();}catch(e){}}
function hH(t,f){if(!t)return;if(ss==='idle'){if(t.includes('hey wordy')){ss='activated';setL(false);wSay('mmm-hmm?',()=>{ss='awaiting_define';setL(true);setS('listening...');});}return;}if(ss==='awaiting_define'){if((t.includes('define')||t.includes('what does')||t.includes('mean'))&&f){ss='defining';document.getElementById('wd').classList.add('vis');document.getElementById('sbot').classList.add('cmp');wSay(`${PH.word} is an ${PH.pos}, meaning ${PH.def} Would you like to record a sentence?`,()=>{ss='awaiting_yes_no';setL(true);setS('say yes or no...');});}return;}if(ss==='awaiting_yes_no'){if(f){if(t.includes('yes')){ss='rec_sent';setS('recording...');document.getElementById('rdot').classList.add('on');document.getElementById('vsent').textContent='';}else if(t.includes('no')){ss='fin';document.getElementById('rdot').classList.remove('on');wSay(`Okay, gotcha. I will only add ${PH.word} and its definition to your library.`,()=>{document.getElementById('ach').classList.add('pop');setTimeout(()=>{ss='done';setTimeout(iSess,2500);},1000);});}}return;}if(ss==='rec_sent'){document.getElementById('vsent').textContent='\u201c'+t+'\u201d';if(f&&t.length>10){ss='fin';document.getElementById('rdot').classList.remove('on');wSay(`Got it! ${PH.word} is on your list.`,()=>{document.getElementById('ach').classList.add('pop');setTimeout(()=>{ss='done';setTimeout(iSess,2500);},1000);});}}}